name: example-environment
channels:
  - default
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - requests
  - plotly
  - seaborn
  - traitlets
  - vega_datasets
  - pip:
    - dx
    - vdom
